const GET_ALL_SEIYUU = 'GET_ALL_SEIYUU'
const GET_ALL_SEIYUU_START = 'GET_ALL_SEIYUU_START'
const GET_ALL_SEIYUU_STOP = 'GET_ALL_SEIYUU_STOP'
const BASE_URL = 'https://graphql.anilist.co'

export { GET_ALL_SEIYUU, GET_ALL_SEIYUU_START, GET_ALL_SEIYUU_STOP, BASE_URL }